In [26]:
# test
import numpy as np


A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12], [32, 40, -1]])
b = np.array([9, 15, 35, 2])
x = np.linalg.solve(A, b)

LinAlgError: Last 2 dimensions of the array must be square

### Thursday

In [21]:
# # 3D Robo frame (mm)
# Robo1 = np.array([-95.85, 563.24, -186])
# Robo2 = np.array([189.08, 573.39, -186])
# Robo3 = np.array([39.65, 565.07, -186])

# # 2D Camera frame (px: (x,y))
# Cam1 = np.array([418, 312]) # green block
# Cam2 = np.array([140, 318]) # red block
# Cam3 = np.array([288, 308]) # blue block

### Friday
* ensure high variance in both axes
* downward gripper orientation during measurement and during stacking with separate command

In [7]:
import numpy as np
# 3D Robo frame (mm)
Robo1 = np.array([113.73094, 478.43097, 100])
Robo2 = np.array([-202.3398, 521.03962, 100]) #210.1615
Robo3 = np.array([-65.02234, 641.59127, 100])

# 2D Camera frame (px: (x,y))
Cam1 = np.array([157, 202]) # green block
Cam2 = np.array([486, 287]) # red block
Cam3 = np.array([322, 395]) # blue block

In [8]:
#for a b c does not work for variables, we have to use it with our measured values as in the example above
import numpy as np

# A = np.array([[X1, Y1, Z1], [X2, Y2, Z2], [X3, Y3, Z3]])
A = np.array([Robo1, Robo2, Robo3])

# bx = np.array([x1, x2, x3])
bx = np.array([Cam1[0], Cam2[0], Cam3[0]])

xi = np.linalg.solve(A, bx)
print(xi)

# check if solution is correct
print(np.allclose(np.dot(A, xi), bx))

[-1.06132696 -0.15148094  3.50178886]
True


In [9]:
#for d e f does not work for variables, we have to use it with our measured values as in the example above
import numpy as np

# by = np.array([y1, y2, y3])
by = np.array([Cam1[1], Cam2[1], Cam3[1]])

xii = np.linalg.solve(A, by)
print(xii)

# check if solution is correct
print(np.allclose(np.dot(A, xii), by))

[-0.12843397  1.04217758 -2.82003114]
True


In [10]:
import numpy as np
TrafoMatrix = np.array([xi, xii, [0,0,1]])
print(TrafoMatrix)
print()
invTrafoMatrix = np.linalg.inv(TrafoMatrix)
print(invTrafoMatrix)

[[-1.06132696 -0.15148094  3.50178886]
 [-0.12843397  1.04217758 -2.82003114]
 [ 0.          0.          1.        ]]

[[-0.9259303  -0.13458435  2.86288037]
 [-0.1141081   0.94294371  3.05871312]
 [ 0.          0.          1.        ]]


In [11]:
TrafoMatrix@invTrafoMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])