In [15]:
import numpy as np

Credits to: https://github.com/heretic1993/autoCalibration

In [78]:
Robo1 = [-0.01,251.14,208.73]
Robo2 = [26.83,188.36,473.59]
Robo3 = [71.17,526.10,18.00]
Robo4 = [110.59,429.92,285.81]
Robo5 = [65.65,198.20,435.28]
Robo6 = [226.00,477.19,-46.48]
Robo7 = [206.72,353.95,339.27]
Robo8 = [93.55,109.99,471.64]
Robo9 = [418.05,358.83,-27.28]

Robo10 = [408.41,234.29,265.65]
Robo11 = [201.19,72.41,456.05]
Robo12 = [531.98,88.46,108.16]
Robo13 = [438.18,-2.58,308.79]
Robo14 = [534.02,-105.82,83.16]
Robo15 = [423.42,-122.20,305.81]
Robo16 = [244.01,-93.70,438.77]
Robo17 = [478.41,-266.70,61.52]
Robo18 = [488.16,-71.63,228.49]

Robo19 = [302.37,-35.99,417.84]
Robo20 = [415.80,-343.60,107.68]
Robo21 = [182.87,-230.46,423.33]
Robo22 = [249.03,-433.05,216.83]
Robo23 = [116.02,-331.25,388.71]

Robo = []
Robo.append(Robo1)
Robo.append(Robo2)
Robo.append(Robo3)
Robo.append(Robo4)
Robo.append(Robo5)
Robo.append(Robo6)
Robo.append(Robo7)
Robo.append(Robo8)
Robo.append(Robo9)
Robo.append(Robo10)
Robo.append(Robo11)
Robo.append(Robo12)
Robo.append(Robo13)
Robo.append(Robo14)
Robo.append(Robo15)
Robo.append(Robo16)
Robo.append(Robo17)
Robo.append(Robo18)
Robo.append(Robo19)
Robo.append(Robo20)
Robo.append(Robo21)
Robo.append(Robo22)
Robo.append(Robo23)

Robo

[[-0.01, 251.14, 208.73],
 [26.83, 188.36, 473.59],
 [71.17, 526.1, 18.0],
 [110.59, 429.92, 285.81],
 [65.65, 198.2, 435.28],
 [226.0, 477.19, -46.48],
 [206.72, 353.95, 339.27],
 [93.55, 109.99, 471.64],
 [418.05, 358.83, -27.28],
 [408.41, 234.29, 265.65],
 [201.19, 72.41, 456.05],
 [531.98, 88.46, 108.16],
 [438.18, -2.58, 308.79],
 [534.02, -105.82, 83.16],
 [423.42, -122.2, 305.81],
 [244.01, -93.7, 438.77],
 [478.41, -266.7, 61.52],
 [488.16, -71.63, 228.49],
 [302.37, -35.99, 417.84],
 [415.8, -343.6, 107.68],
 [182.87, -230.46, 423.33],
 [249.03, -433.05, 216.83],
 [116.02, -331.25, 388.71]]

In [79]:
Cam1 = [387,270,2259] # green block
Cam2 = [381,186,2214] # red block
Cam3 = [445,331,2188] # blue block
Cam4 = [438,258,2138]
Cam5 = [383,202,2139]
Cam6 = [434,362,2084]
Cam7 = [424,247,2002]
Cam8 = [354,188,2069]
Cam9 = [410,379,1893]
Cam10 = [386,288,1785] # green block
Cam11 = [333,200,1926] # red block
Cam12 = [329,353,1763] # blue block
Cam13 = [297,276,1754]
Cam14 = [260,360,1745]
Cam15 = [252,274,1746]
Cam16 = [262,209,1874]
Cam17 = [208,358,1773]
Cam18 = [272,308,1742]
Cam19 = [286,222,1802] # green block
Cam20 = [183,337,1836] # red block
Cam21 = [213,211,1959] # blue block
Cam22 = [161,286,1976]
Cam23 = [187,220,2098]

Cam = []
Cam.append(Cam1)
Cam.append(Cam2)
Cam.append(Cam3)
Cam.append(Cam4)
Cam.append(Cam5)
Cam.append(Cam6)
Cam.append(Cam7)
Cam.append(Cam8)
Cam.append(Cam9)
Cam.append(Cam10)
Cam.append(Cam11)
Cam.append(Cam12)
Cam.append(Cam13)
Cam.append(Cam14)
Cam.append(Cam15)
Cam.append(Cam16)
Cam.append(Cam17)
Cam.append(Cam18)
Cam.append(Cam19)
Cam.append(Cam20)
Cam.append(Cam21)
Cam.append(Cam22)
Cam.append(Cam23)

Cam

[[387, 270, 2259],
 [381, 186, 2214],
 [445, 331, 2188],
 [438, 258, 2138],
 [383, 202, 2139],
 [434, 362, 2084],
 [424, 247, 2002],
 [354, 188, 2069],
 [410, 379, 1893],
 [386, 288, 1785],
 [333, 200, 1926],
 [329, 353, 1763],
 [297, 276, 1754],
 [260, 360, 1745],
 [252, 274, 1746],
 [262, 209, 1874],
 [208, 358, 1773],
 [272, 308, 1742],
 [286, 222, 1802],
 [183, 337, 1836],
 [213, 211, 1959],
 [161, 286, 1976],
 [187, 220, 2098]]

In [82]:
# Robo Calibration points
np_robo_cali_points = np.array(Robo)
arm_cord = np.column_stack((np_robo_cali_points[:,0:3], np.ones(np_robo_cali_points.shape[0]).T)).T
arm_cord

array([[-1.0000e-02,  2.6830e+01,  7.1170e+01,  1.1059e+02,  6.5650e+01,
         2.2600e+02,  2.0672e+02,  9.3550e+01,  4.1805e+02,  4.0841e+02,
         2.0119e+02,  5.3198e+02,  4.3818e+02,  5.3402e+02,  4.2342e+02,
         2.4401e+02,  4.7841e+02,  4.8816e+02,  3.0237e+02,  4.1580e+02,
         1.8287e+02,  2.4903e+02,  1.1602e+02],
       [ 2.5114e+02,  1.8836e+02,  5.2610e+02,  4.2992e+02,  1.9820e+02,
         4.7719e+02,  3.5395e+02,  1.0999e+02,  3.5883e+02,  2.3429e+02,
         7.2410e+01,  8.8460e+01, -2.5800e+00, -1.0582e+02, -1.2220e+02,
        -9.3700e+01, -2.6670e+02, -7.1630e+01, -3.5990e+01, -3.4360e+02,
        -2.3046e+02, -4.3305e+02, -3.3125e+02],
       [ 2.0873e+02,  4.7359e+02,  1.8000e+01,  2.8581e+02,  4.3528e+02,
        -4.6480e+01,  3.3927e+02,  4.7164e+02, -2.7280e+01,  2.6565e+02,
         4.5605e+02,  1.0816e+02,  3.0879e+02,  8.3160e+01,  3.0581e+02,
         4.3877e+02,  6.1520e+01,  2.2849e+02,  4.1784e+02,  1.0768e+02,
         4.2333e+02,  2.1683

In [83]:
centers=np.ones(arm_cord.shape)
for ind,pt in enumerate(np_robo_cali_points):
    print(str(ind + 1), ". Robo Point:", pt)
    centers[0:3,ind] = Cam[ind]
    print(str(ind + 1), ". Camera Point:", centers[0:3,ind])

1 . Robo Point: [-1.0000e-02  2.5114e+02  2.0873e+02]
1 . Camera Point: [ 387.  270. 2259.]
2 . Robo Point: [ 26.83 188.36 473.59]
2 . Camera Point: [ 381.  186. 2214.]
3 . Robo Point: [ 71.17 526.1   18.  ]
3 . Camera Point: [ 445.  331. 2188.]
4 . Robo Point: [110.59 429.92 285.81]
4 . Camera Point: [ 438.  258. 2138.]
5 . Robo Point: [ 65.65 198.2  435.28]
5 . Camera Point: [ 383.  202. 2139.]
6 . Robo Point: [226.   477.19 -46.48]
6 . Camera Point: [ 434.  362. 2084.]
7 . Robo Point: [206.72 353.95 339.27]
7 . Camera Point: [ 424.  247. 2002.]
8 . Robo Point: [ 93.55 109.99 471.64]
8 . Camera Point: [ 354.  188. 2069.]
9 . Robo Point: [418.05 358.83 -27.28]
9 . Camera Point: [ 410.  379. 1893.]
10 . Robo Point: [408.41 234.29 265.65]
10 . Camera Point: [ 386.  288. 1785.]
11 . Robo Point: [201.19  72.41 456.05]
11 . Camera Point: [ 333.  200. 1926.]
12 . Robo Point: [531.98  88.46 108.16]
12 . Camera Point: [ 329.  353. 1763.]
13 . Robo Point: [438.18  -2.58 308.79]
13 . Camera Poi

In [84]:
np_cam_cali_points = np.array(Cam)
centers = np.column_stack((np_cam_cali_points[:], np.ones(np_cam_cali_points.shape[0]).T)).T
centers

array([[3.870e+02, 3.810e+02, 4.450e+02, 4.380e+02, 3.830e+02, 4.340e+02,
        4.240e+02, 3.540e+02, 4.100e+02, 3.860e+02, 3.330e+02, 3.290e+02,
        2.970e+02, 2.600e+02, 2.520e+02, 2.620e+02, 2.080e+02, 2.720e+02,
        2.860e+02, 1.830e+02, 2.130e+02, 1.610e+02, 1.870e+02],
       [2.700e+02, 1.860e+02, 3.310e+02, 2.580e+02, 2.020e+02, 3.620e+02,
        2.470e+02, 1.880e+02, 3.790e+02, 2.880e+02, 2.000e+02, 3.530e+02,
        2.760e+02, 3.600e+02, 2.740e+02, 2.090e+02, 3.580e+02, 3.080e+02,
        2.220e+02, 3.370e+02, 2.110e+02, 2.860e+02, 2.200e+02],
       [2.259e+03, 2.214e+03, 2.188e+03, 2.138e+03, 2.139e+03, 2.084e+03,
        2.002e+03, 2.069e+03, 1.893e+03, 1.785e+03, 1.926e+03, 1.763e+03,
        1.754e+03, 1.745e+03, 1.746e+03, 1.874e+03, 1.773e+03, 1.742e+03,
        1.802e+03, 1.836e+03, 1.959e+03, 1.976e+03, 2.098e+03],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000

In [85]:
centers.T

array([[3.870e+02, 2.700e+02, 2.259e+03, 1.000e+00],
       [3.810e+02, 1.860e+02, 2.214e+03, 1.000e+00],
       [4.450e+02, 3.310e+02, 2.188e+03, 1.000e+00],
       [4.380e+02, 2.580e+02, 2.138e+03, 1.000e+00],
       [3.830e+02, 2.020e+02, 2.139e+03, 1.000e+00],
       [4.340e+02, 3.620e+02, 2.084e+03, 1.000e+00],
       [4.240e+02, 2.470e+02, 2.002e+03, 1.000e+00],
       [3.540e+02, 1.880e+02, 2.069e+03, 1.000e+00],
       [4.100e+02, 3.790e+02, 1.893e+03, 1.000e+00],
       [3.860e+02, 2.880e+02, 1.785e+03, 1.000e+00],
       [3.330e+02, 2.000e+02, 1.926e+03, 1.000e+00],
       [3.290e+02, 3.530e+02, 1.763e+03, 1.000e+00],
       [2.970e+02, 2.760e+02, 1.754e+03, 1.000e+00],
       [2.600e+02, 3.600e+02, 1.745e+03, 1.000e+00],
       [2.520e+02, 2.740e+02, 1.746e+03, 1.000e+00],
       [2.620e+02, 2.090e+02, 1.874e+03, 1.000e+00],
       [2.080e+02, 3.580e+02, 1.773e+03, 1.000e+00],
       [2.720e+02, 3.080e+02, 1.742e+03, 1.000e+00],
       [2.860e+02, 2.220e+02, 1.802e+03, 1.000

In [86]:
image_to_arm = np.dot(arm_cord, np.linalg.pinv(centers))
arm_to_image = np.linalg.pinv(image_to_arm)

In [90]:
print("Finished")
print("Image to arm transform:\n", image_to_arm)
print("Arm to Image transform:\n", arm_to_image)
print()
print()

print("-------------------")
print("-------------------")
print("-------------------")
print("Sanity Test: Image_to_Arm")
print("-------------------")
print("-------------------")
print("-------------------")
print()
for ind, pt in enumerate(centers.T):
    print("Spectated Camera Point:", np.array(pt)[0:3])
    print("Expected Robo Point:", np_robo_cali_points[ind][0:3]) #default_cali_point
    print("Resulting Robo Point:", np.dot(image_to_arm, np.array(pt))[0:3])
    print("")
    
print("-------------------")    
print("-------------------")
print("-------------------")
print("Sanity Test: Arm_to_Image")
print("-------------------")
print("-------------------")
print("-------------------")
print()
for ind, pt in enumerate(np_robo_cali_points):
    print("Spectated Robo Point:", np.array(pt)[0:3])
    print("Expected Camera Point:", centers.T[ind][0:3])
    pt[3]=1
    print("Resulting Camera Point:", np.dot(arm_to_image, np.array(pt))[0:3])
    print("")

Finished
Image to arm transform:
 [[ 1.17387918e-02  9.06677568e-01 -8.19763438e-01  1.61342946e+03]
 [ 2.98177269e+00  3.59008659e-01  3.71671350e-02 -1.06108133e+03]
 [ 1.62125309e-02 -2.82591617e+00 -2.35226662e-01  1.48935144e+03]
 [-8.67361738e-19  8.40256684e-19 -1.08420217e-19  1.00000000e+00]]
Arm to Image transform:
 [[ 2.72655271e-03  3.35123992e-01  4.34494557e-02  2.86483202e+02]
 [ 9.29915505e-02  1.39477232e-03 -3.23854586e-01  3.33777953e+02]
 [-1.11697424e+00  6.34153623e-03 -3.57568576e-01  2.34143330e+03]
 [ 3.08076047e-16  1.19099778e-15  5.14074460e-16  1.00000000e+00]]


-------------------
-------------------
-------------------
Sanity Test: Image_to_Arm
-------------------
-------------------
-------------------

Spectated Camera Point: [ 387.  270. 2259.]
Expected Robo Point: [-1.0000e-02  2.5114e+02  2.0873e+02]
Resulting Robo Point: [ 10.92970958 273.75759623 201.25128926]

Spectated Camera Point: [ 381.  186. 2214.]
Expected Robo Point: [ 26.83 188.36 473.59]

IndexError: index 3 is out of bounds for axis 0 with size 3