In [1]:
import numpy as np

Credits to: https://github.com/heretic1993/autoCalibration

In [2]:
Robo1 = [-221.63,449.19,-108.02,0]
Robo2 = [57.03,296.45,504.09,0]
Robo3 = [377.84,545.41,-0.86,0]
Robo4 = [437.44,124.65,481.03,0]
Robo5 = [713.23,187.79,80.57,0]
Robo6 = [596.38,-196.88,58.72,0]
Robo7 = [542.61,-365.15,293.54,0]
Robo8 = [211.25,-427.34,487.84,0]
Robo9 = [694.05,-4.92,223.01,0]

Robo = []
Robo.append(Robo1)
Robo.append(Robo2)
Robo.append(Robo3)
Robo.append(Robo4)
Robo.append(Robo5)
Robo.append(Robo6)
Robo.append(Robo7)
Robo.append(Robo8)
Robo.append(Robo9)

Robo

[[-221.63, 449.19, -108.02, 0],
 [57.03, 296.45, 504.09, 0],
 [377.84, 545.41, -0.86, 0],
 [437.44, 124.65, 481.03, 0],
 [713.23, 187.79, 80.57, 0],
 [596.38, -196.88, 58.72, 0],
 [542.61, -365.15, 293.54, 0],
 [211.25, -427.34, 487.84, 0],
 [694.05, -4.92, 223.01, 0]]

In [3]:
Cam1 = [444,312,2406] # green block
Cam2 = [417,176,2084] # red block
Cam3 = [497,348,1911] # blue block
Cam4 = [351,191,1747]
Cam5 = [401,354,1529]
Cam6 = [247,356,1671]
Cam7 = [185,252,1753]
Cam8 = [184,170,1952]
Cam9 = [321,301,1549]

Cam = []
Cam.append(Cam1)
Cam.append(Cam2)
Cam.append(Cam3)
Cam.append(Cam4)
Cam.append(Cam5)
Cam.append(Cam6)
Cam.append(Cam7)
Cam.append(Cam8)
Cam.append(Cam9)

Cam

[[444, 312, 2406],
 [417, 176, 2084],
 [497, 348, 1911],
 [351, 191, 1747],
 [401, 354, 1529],
 [247, 356, 1671],
 [185, 252, 1753],
 [184, 170, 1952],
 [321, 301, 1549]]

In [9]:
# Robo Calibration points
np_robo_cali_points = np.array(Robo)
arm_cord = np.column_stack((np_robo_cali_points[:,0:3], np.ones(np_robo_cali_points.shape[0]).T)).T
arm_cord

array([[-221.63,   57.03,  377.84,  437.44,  713.23,  596.38,  542.61,
         211.25,  694.05],
       [ 449.19,  296.45,  545.41,  124.65,  187.79, -196.88, -365.15,
        -427.34,   -4.92],
       [-108.02,  504.09,   -0.86,  481.03,   80.57,   58.72,  293.54,
         487.84,  223.01],
       [   1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,
           1.  ,    1.  ]])

In [10]:
centers=np.ones(arm_cord.shape)
for ind,pt in enumerate(np_robo_cali_points):
    print(str(ind + 1), ". Robo Point:", pt)
    centers[0:3,ind] = Cam[ind]
    print(str(ind + 1), ". Camera Point:", centers[0:3,ind])

1 . Robo Point: [-221.63  449.19 -108.02    0.  ]
1 . Camera Point: [ 444.  312. 2406.]
2 . Robo Point: [ 57.03 296.45 504.09   0.  ]
2 . Camera Point: [ 417.  176. 2084.]
3 . Robo Point: [377.84 545.41  -0.86   0.  ]
3 . Camera Point: [ 497.  348. 1911.]
4 . Robo Point: [437.44 124.65 481.03   0.  ]
4 . Camera Point: [ 351.  191. 1747.]
5 . Robo Point: [713.23 187.79  80.57   0.  ]
5 . Camera Point: [ 401.  354. 1529.]
6 . Robo Point: [ 596.38 -196.88   58.72    0.  ]
6 . Camera Point: [ 247.  356. 1671.]
7 . Robo Point: [ 542.61 -365.15  293.54    0.  ]
7 . Camera Point: [ 185.  252. 1753.]
8 . Robo Point: [ 211.25 -427.34  487.84    0.  ]
8 . Camera Point: [ 184.  170. 1952.]
9 . Robo Point: [694.05  -4.92 223.01   0.  ]
9 . Camera Point: [ 321.  301. 1549.]


In [11]:
centers.T

array([[4.440e+02, 3.120e+02, 2.406e+03, 1.000e+00],
       [4.170e+02, 1.760e+02, 2.084e+03, 1.000e+00],
       [4.970e+02, 3.480e+02, 1.911e+03, 1.000e+00],
       [3.510e+02, 1.910e+02, 1.747e+03, 1.000e+00],
       [4.010e+02, 3.540e+02, 1.529e+03, 1.000e+00],
       [2.470e+02, 3.560e+02, 1.671e+03, 1.000e+00],
       [1.850e+02, 2.520e+02, 1.753e+03, 1.000e+00],
       [1.840e+02, 1.700e+02, 1.952e+03, 1.000e+00],
       [3.210e+02, 3.010e+02, 1.549e+03, 1.000e+00]])

In [12]:
image_to_arm = np.dot(arm_cord, np.linalg.pinv(centers))
arm_to_image = np.linalg.pinv(image_to_arm)

In [13]:
print("Finished")
print("Image to arm transform:\n", image_to_arm)
print("Arm to Image transform:\n", arm_to_image)
print()
print()

print("-------------------")
print("-------------------")
print("-------------------")
print("Sanity Test: Image_to_Arm")
print("-------------------")
print("-------------------")
print("-------------------")
print()
for ind, pt in enumerate(centers.T):
    print("Spectated Camera Point:", np.array(pt)[0:3])
    print("Expected Robo Point:", np_robo_cali_points[ind][0:3]) #default_cali_point
    print("Resulting Robo Point:", np.dot(image_to_arm, np.array(pt))[0:3])
    print("")
    
print("-------------------")    
print("-------------------")
print("-------------------")
print("Sanity Test: Arm_to_Image")
print("-------------------")
print("-------------------")
print("-------------------")
print()
for ind, pt in enumerate(np_robo_cali_points):
    print("Spectated Robo Point:", np.array(pt)[0:3])
    print("Expected Camera Point:", centers.T[ind][0:3])
    pt[3]=1
    print("Resulting Camera Point:", np.dot(arm_to_image, np.array(pt))[0:3])
    print("")

Finished
Image to arm transform:
 [[-1.38537711e-01  5.36769204e-01 -1.04725998e+00  2.21072026e+03]
 [ 2.90797523e+00  1.29089884e-01  1.06705665e-01 -1.14894323e+03]
 [ 1.13721285e-01 -3.09858547e+00 -3.44271153e-01  1.66794680e+03]
 [-9.75781955e-19 -3.25260652e-19  1.08420217e-19  1.00000000e+00]]
Arm to Image transform:
 [[ 2.87457598e-02  3.44495353e-01  1.93316287e-02  3.00012643e+02]
 [ 1.01773795e-01  1.67526287e-02 -3.04399661e-01  3.01976868e+02]
 [-9.06511614e-01 -3.69853747e-02 -1.58576215e-01  2.22604618e+03]
 [ 7.04731412e-18  5.31286170e-16  3.54547663e-16  1.00000000e+00]]


-------------------
-------------------
-------------------
Sanity Test: Image_to_Arm
-------------------
-------------------
-------------------

Spectated Camera Point: [ 444.  312. 2406.]
Expected Robo Point: [-221.63  449.19 -108.02]
Resulting Robo Point: [-203.02600108  439.20764422  -76.63601227]

Spectated Camera Point: [ 417.  176. 2084.]
Expected Robo Point: [ 57.03 296.45 504.09]
Resultin