In [10]:
import numpy as np

Credits to: https://github.com/heretic1993/autoCalibration

In [11]:
Robo1 = [5.79, 438.16, 379.02]
Robo2 = [171.07, 546.43, 167.22]
Robo3 = [296.60, 450.95, 244.06]
Robo4 = [133.85, 103.18, 463.00]
Robo5 = [460.65, 205.18, 287.03]
Robo6 = [647.19, 35.69, 85.67]
Robo7 = [468.88, -230.24, 201.38]
Robo8 = [340.80, -450.50, 26.39]
Robo9 = [104.79, -311.25, 407.06]

#Robo10 = [408.41,234.29,265.65]
#Robo11 = [201.19,72.41,456.05]
#Robo12 = [531.98,88.46,108.16]
#Robo13 = [438.18,-2.58,308.79]
#Robo14 = [534.02,-105.82,83.16]
#Robo15 = [423.42,-122.20,305.81]
#Robo16 = [244.01,-93.70,438.77]
#Robo17 = [478.41,-266.70,61.52]
#Robo18 = [488.16,-71.63,228.49]

#Robo19 = [302.37,-35.99,417.84]
#Robo20 = [415.80,-343.60,107.68]
#Robo21 = [182.87,-230.46,423.33]
#Robo22 = [249.03,-433.05,216.83]
#Robo23 = [116.02,-331.25,388.71]

Robo = []
Robo.append(Robo1)
Robo.append(Robo2)
Robo.append(Robo3)
Robo.append(Robo4)
Robo.append(Robo5)
Robo.append(Robo6)
Robo.append(Robo7)
Robo.append(Robo8)
Robo.append(Robo9)
#Robo.append(Robo10)
#Robo.append(Robo11)
#Robo.append(Robo12)
#Robo.append(Robo13)
#Robo.append(Robo14)
#Robo.append(Robo15)
#Robo.append(Robo16)
#Robo.append(Robo17)
#Robo.append(Robo18)
#Robo.append(Robo19)
#Robo.append(Robo20)
#Robo.append(Robo21)
#Robo.append(Robo22)
#Robo.append(Robo23)

Robo

[[5.79, 438.16, 379.02],
 [171.07, 546.43, 167.22],
 [296.6, 450.95, 244.06],
 [133.85, 103.18, 463.0],
 [460.65, 205.18, 287.03],
 [647.19, 35.69, 85.67],
 [468.88, -230.24, 201.38],
 [340.8, -450.5, 26.39],
 [104.79, -311.25, 407.06]]

In [12]:
Cam1 = [403, 235, 3350] # green block
Cam2 = [403, 235, 3243] # red block
Cam3 = [407, 272, 3064] # blue block
Cam4 = [340, 220, 3079]
Cam5 = [357, 269, 2772]
Cam6 = [316, 321, 2704]
Cam7 = [254, 287, 2880]
Cam8 = [214, 317, 2928]
Cam9 = [235, 230, 3109]
#Cam10 = [386,288,1785] # green block
#Cam11 = [333,200,1926] # red block
#Cam12 = [329,353,1763] # blue block
#Cam13 = [297,276,1754]
#Cam14 = [260,360,1745]
#Cam15 = [252,274,1746]
#Cam16 = [262,209,1874]
#Cam17 = [208,358,1773]
#Cam18 = [272,308,1742]
#Cam19 = [286,222,1802] # green block
#Cam20 = [183,337,1836] # red block
#Cam21 = [213,211,1959] # blue block
#Cam22 = [161,286,1976]
#C#am23 = [187,220,2098]

Cam = []
Cam.append(Cam1)
Cam.append(Cam2)
Cam.append(Cam3)
Cam.append(Cam4)
Cam.append(Cam5)
Cam.append(Cam6)
Cam.append(Cam7)
Cam.append(Cam8)
Cam.append(Cam9)
#Cam.append(Cam10)
#Cam.append(Cam11)
#Cam.append(Cam12)
#Cam.append(Cam13)
#Cam.append(Cam14)
#Cam.append(Cam15)
#Cam.append(Cam16)
#Cam.append(Cam17)
#Cam.append(Cam18)
#Cam.append(Cam19)
#Cam.append(Cam20)
#Cam.append(Cam21)
#Cam.append(Cam22)
#Cam.append(Cam23)

Cam

[[403, 235, 3350],
 [403, 235, 3243],
 [407, 272, 3064],
 [340, 220, 3079],
 [357, 269, 2772],
 [316, 321, 2704],
 [254, 287, 2880],
 [214, 317, 2928],
 [235, 230, 3109]]

In [13]:
# Robo Calibration points
np_robo_cali_points = np.array(Robo)
arm_cord = np.column_stack((np_robo_cali_points[:,0:3], np.ones(np_robo_cali_points.shape[0]).T)).T
arm_cord

array([[   5.79,  171.07,  296.6 ,  133.85,  460.65,  647.19,  468.88,
         340.8 ,  104.79],
       [ 438.16,  546.43,  450.95,  103.18,  205.18,   35.69, -230.24,
        -450.5 , -311.25],
       [ 379.02,  167.22,  244.06,  463.  ,  287.03,   85.67,  201.38,
          26.39,  407.06],
       [   1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,    1.  ,
           1.  ,    1.  ]])

In [14]:
centers=np.ones(arm_cord.shape)
for ind,pt in enumerate(np_robo_cali_points):
    print(str(ind + 1), ". Robo Point:", pt)
    centers[0:3,ind] = Cam[ind]
    print(str(ind + 1), ". Camera Point:", centers[0:3,ind])

1 . Robo Point: [  5.79 438.16 379.02]
1 . Camera Point: [ 403.  235. 3350.]
2 . Robo Point: [171.07 546.43 167.22]
2 . Camera Point: [ 403.  235. 3243.]
3 . Robo Point: [296.6  450.95 244.06]
3 . Camera Point: [ 407.  272. 3064.]
4 . Robo Point: [133.85 103.18 463.  ]
4 . Camera Point: [ 340.  220. 3079.]
5 . Robo Point: [460.65 205.18 287.03]
5 . Camera Point: [ 357.  269. 2772.]
6 . Robo Point: [647.19  35.69  85.67]
6 . Camera Point: [ 316.  321. 2704.]
7 . Robo Point: [ 468.88 -230.24  201.38]
7 . Camera Point: [ 254.  287. 2880.]
8 . Robo Point: [ 340.8  -450.5    26.39]
8 . Camera Point: [ 214.  317. 2928.]
9 . Robo Point: [ 104.79 -311.25  407.06]
9 . Camera Point: [ 235.  230. 3109.]


In [15]:
np_cam_cali_points = np.array(Cam)
centers = np.column_stack((np_cam_cali_points[:], np.ones(np_cam_cali_points.shape[0]).T)).T
centers

array([[4.030e+02, 4.030e+02, 4.070e+02, 3.400e+02, 3.570e+02, 3.160e+02,
        2.540e+02, 2.140e+02, 2.350e+02],
       [2.350e+02, 2.350e+02, 2.720e+02, 2.200e+02, 2.690e+02, 3.210e+02,
        2.870e+02, 3.170e+02, 2.300e+02],
       [3.350e+03, 3.243e+03, 3.064e+03, 3.079e+03, 2.772e+03, 2.704e+03,
        2.880e+03, 2.928e+03, 3.109e+03],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 1.000e+00, 1.000e+00]])

In [16]:
centers.T

array([[4.030e+02, 2.350e+02, 3.350e+03, 1.000e+00],
       [4.030e+02, 2.350e+02, 3.243e+03, 1.000e+00],
       [4.070e+02, 2.720e+02, 3.064e+03, 1.000e+00],
       [3.400e+02, 2.200e+02, 3.079e+03, 1.000e+00],
       [3.570e+02, 2.690e+02, 2.772e+03, 1.000e+00],
       [3.160e+02, 3.210e+02, 2.704e+03, 1.000e+00],
       [2.540e+02, 2.870e+02, 2.880e+03, 1.000e+00],
       [2.140e+02, 3.170e+02, 2.928e+03, 1.000e+00],
       [2.350e+02, 2.300e+02, 3.109e+03, 1.000e+00]])

In [17]:
image_to_arm = np.dot(arm_cord, np.linalg.pinv(centers))
arm_to_image = np.linalg.pinv(image_to_arm)

In [18]:
print("Finished")
print("Image to arm transform:\n", image_to_arm)
print("Arm to Image transform:\n", arm_to_image)
print()
print()

print("-------------------")
print("-------------------")
print("-------------------")
print("Sanity Test: Image_to_Arm")
print("-------------------")
print("-------------------")
print("-------------------")
print()
for ind, pt in enumerate(centers.T):
    print("Spectated Camera Point:", np.array(pt)[0:3])
    print("Expected Robo Point:", np_robo_cali_points[ind][0:3]) #default_cali_point
    print("Resulting Robo Point:", np.dot(image_to_arm, np.array(pt))[0:3])
    print("")
    
print("-------------------")    
print("-------------------")
print("-------------------")
print("Sanity Test: Arm_to_Image")
print("-------------------")
print("-------------------")
print("-------------------")
print()
for ind, pt in enumerate(np_robo_cali_points):
    print("Spectated Robo Point:", np.array(pt)[0:3])
    print("Expected Camera Point:", centers.T[ind][0:3])
    pt[3]=1
    print("Resulting Camera Point:", np.dot(arm_to_image, np.array(pt))[0:3])
    print("")

Finished
Image to arm transform:
 [[ 5.68192779e-01  1.95014068e+00 -7.38910498e-01  1.81758340e+03]
 [ 4.63951488e+00  2.17799140e-01  1.03736906e-01 -1.79283182e+03]
 [-1.10971419e-01 -4.54328774e+00 -2.60702910e-01  2.27763990e+03]
 [-2.60208521e-18 -1.73472348e-18 -3.79470760e-19  1.00000000e+00]]
Arm to Image transform:
 [[ 2.28650599e-02  2.13218769e-01  2.00359197e-02  2.95071630e+02]
 [ 6.60824393e-02 -1.26937306e-02 -1.92348511e-01  2.95232574e+02]
 [-1.16135606e+00  1.30455319e-01 -4.92241472e-01  3.46589476e+03]
 [ 2.97179815e-16  1.05173709e-15  5.99672222e-16  1.00000000e+00]]


-------------------
-------------------
-------------------
Sanity Test: Image_to_Arm
-------------------
-------------------
-------------------

Spectated Camera Point: [ 403.  235. 3350.]
Expected Robo Point: [  5.79 438.16 379.02]
Resulting Robo Point: [ 29.49798002 475.59411279 291.89104833]

Spectated Camera Point: [ 403.  235. 3243.]
Expected Robo Point: [171.07 546.43 167.22]
Resulting Robo

IndexError: index 3 is out of bounds for axis 0 with size 3