In [48]:
import numpy as np
# 3D Robo frame (mm)
Robo1 = np.array([271.56,0.05,189.75])
Robo2 = np.array([145.73,-125.99,437.63]) #210.1615
Robo3 = np.array([397.66,282.08,187.52])
Robo4 = np.array([524.74,153.28,-33.01])
Robo5 = np.array([537.16,-127.98,264.69])
Robo6 = np.array([240.20,128.40,470.06])
Robo7 = np.array([320.84,-160.40,423.57])
Robo8 = np.array([542.04,-95.88,183.95])
Robo9 = np.array([410.86,72.29,-42.20])


# 3D Camera frame (px: (x,y,z))
Cam1 = np.array([332,271,1968]) # green block
Cam2 = np.array([259,137,2599]) # red block
Cam3 = np.array([471,283,1498]) # blue block
Cam4 = np.array([407,393,1716])
Cam5 = np.array([270,276,1291])
Cam6 = np.array([405,126,2577])
Cam7 = np.array([252,166,2609])
Cam8 = np.array([296,312,1421])
Cam9 = np.array([373,366,1720])


In [49]:
#for a b c does not work for variables, we have to use it with our measured values as in the example above
import numpy as np

# A = np.array([[X1, Y1, Z1], [X2, Y2, Z2], [X3, Y3, Z3]])
A = np.array([Robo1,Robo2,Robo3,Robo4,Robo5, Robo6, Robo7,Robo8, Robo9])
#A = np.array([Robo1,Robo2,Robo3])

In [50]:
#bx = np.array([x1, x2, x3])
bx = np.array([Cam1[0], Cam2[0], Cam3[0],Cam4[0],Cam5[0], Cam6[0], Cam7[0], Cam8[0],Cam9[0]])
#bx = np.array([Cam1[0], Cam2[0], Cam3[0]])
#xi = np.linalg.solve(A, bx)
xi = np.linalg.lstsq(A, bx, rcond=None)[0]
print(xi)

# check if solution is correct
print("Result: " + str(np.allclose(np.dot(A, xi), bx)))

[0.59106074 0.67958998 0.42079333]
Result: False


In [51]:
#for d e f does not work for variables, we have to use it with our measured values as in the example above
# by = np.array([y1, y2, y3])
#by = np.array([Cam1[1], Cam2[1], Cam3[1]])
by = np.array([Cam1[1], Cam2[1], Cam3[1],Cam4[1],Cam5[1], Cam6[1], Cam7[1], Cam8[1],Cam9[1]])
#xii = np.linalg.solve(A, by)
xii = np.linalg.lstsq(A, by, rcond=None)[0]
print(xii)

# check if solution is correct
print("Result: " + str(np.allclose(np.dot(A, xii), by)))

[ 0.68343312  0.14378898 -0.04603198]
Result: False


In [52]:
#for g h i does not work for variables, we have to use it with our measured values as in the example above
# bz = np.array([z1, z2, z3])
#bz = np.array([Cam1[2], Cam2[2], Cam3[2]])
bz = np.array([Cam1[2], Cam2[2], Cam3[2],Cam4[2],Cam5[2], Cam6[2], Cam7[2], Cam8[2],Cam9[2]])
#xiii = np.linalg.solve(A, bz)
xiii = np.linalg.lstsq(A, bz, rcond=None)[0]
print(xiii)

# check if solution is correct
print("Result: " + str(np.allclose(np.dot(A, xiii), bz)))

[2.27099529 1.25099609 4.15946376]
Result: False


In [53]:
import numpy as np
TrafoMatrix = np.array([xi, xii, xiii])
print(TrafoMatrix)
print()
invTrafoMatrix = np.linalg.inv(TrafoMatrix)
print(invTrafoMatrix)

[[ 0.59106074  0.67958998  0.42079333]
 [ 0.68343312  0.14378898 -0.04603198]
 [ 2.27099529  1.25099609  4.15946376]]

[[-0.47068177  1.65131359  0.06589142]
 [ 2.11572391 -1.07885886 -0.22597733]
 [-0.37933887 -0.57711217  0.27240474]]


In [54]:
TrafoMatrix@invTrafoMatrix

array([[ 1.00000000e+00,  2.22776338e-16,  3.31667028e-18],
       [-3.44090879e-17,  1.00000000e+00,  7.88884704e-17],
       [ 9.73201224e-17,  5.39147703e-16,  1.00000000e+00]])